version: '3.9'
services:
    api-nest:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        ports:
            - '${SERVER_PORT}:${SERVER_PORT}'
        volumes:
            - .:/app
        depends_on:
            - database
    database:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
            - DB_URL=${DB_URL}
            - DB_HOST=localhost
        ports:
            - '${DB_PORT}:5432'
